# Generated by Django 4.0.1 on 2022-08-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='superintendent',
            field=models.BooleanField(default=False),
        ),
    ]
