# Generated by Django 4.0.1 on 2022-08-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_superintendent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordAnswer',
            field=models.CharField(error_messages={'max_length': '답변의 길이가 너무 깁니다.'}, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passwordQuestion',
            field=models.CharField(error_messages={'max_length': '질문의 길이가 너무 깁니다.'}, max_length=50, null=True),
        ),
    ]
