# Generated by Django 4.0.1 on 2022-08-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_passwordanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='testPath',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
